name: Xcode CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '15.0'

      - name: Build and test
        run: |
          xcodebuild \
            -project "Newtonian Physics Simulator.xcodeproj" \
            -scheme "Newtonian Physics Simulator iOS" \
            -destination 'platform=iOS Simulator,name=iPhone 16 Pro,OS=18.4' \
            clean build test
